# Generated by Django 4.2.3 on 2023-08-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='dni',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
